# Generated by Django 5.0.2 on 2024-02-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0005_rename_trips_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/vehicles/'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='PENDING', max_length=15),
        ),
    ]
