# Generated by Django 5.0.2 on 2024-02-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0006_vehicle_image_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_location_name',
            field=models.CharField(default='here'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='start_location_name',
            field=models.CharField(default='there'),
            preserve_default=False,
        ),
    ]
