# Generated by Django 5.0.2 on 2024-02-28 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0007_trip_end_location_name_trip_start_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver_id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='driver_id',
            field=models.ForeignKey(default='98c41f6f-3acb-4831-b632-fb8b86e4222e', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='doqa_core.employee'),
            preserve_default=False,
        ),
    ]
