# Generated by Django 5.0.2 on 2024-02-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0008_remove_trip_driver_id_vehicle_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
