# Generated by Django 5.0.2 on 2024-03-01 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0009_alter_maintenance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doqa_core.employee'),
        ),
    ]
