# Generated by Django 5.0.2 on 2024-03-02 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0010_alter_vehicle_driver_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doqa_core.employee'),
        ),
    ]
