# Generated by Django 5.0.2 on 2024-03-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0011_alter_vehicle_driver_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
