# Generated by Django 5.0.2 on 2024-03-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0013_alter_employee_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='route_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
