# Generated by Django 5.0.2 on 2024-03-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0015_trip_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel',
            field=models.FloatField(default=30, null=True),
        ),
    ]
