# Generated by Django 5.0.2 on 2024-03-15 10:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doqa_core', '0016_vehicle_fuel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='value',
        ),
        migrations.RemoveField(
            model_name='report',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='alert',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='inventory',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(default='media/reports'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
